export const Languages = [
  {code: 'en-US', name: 'English (United States)'},
  {code: 'zh-CN', name: 'Chinese, (Mandarin, China)'},
  {code: 'hi-IN', name: 'Hindi (India)'},
  {code: 'te-IN', name: 'Telugu (India)'},
  {code: 'ta-IN', name: 'Tamil (India)'},
  {code: 'ml-IN', name: 'Malayalam (India)'},
  {code: 'mr-IN', name: 'Marathi (India)'},
  {code: 'ne-NP', name: 'Nepali (Nepal)'},
  {code: 'es-MX', name: 'Spanish (Mexico)'},
  {code: 'fr-FR', name: 'French (France)'},
  {code: 'ar-AE', name: 'Arabic (United Arab Emirates)'},
  {code: 'ru-RU', name: 'Russian (Russia)'},
  {code: 'pt-BR', name: 'Portuguese (Brazil)'},
  {code: 'id-ID', name: 'Indonesian (Indonesia)'},
  {code: 'de-DE', name: 'German (Germany)'},
  {code: 'ja-JP', name: 'Japanese (Japan)'},
]; 