export const VoiceData = [
  {name: "Jenny Multi Lingua", code: "en-US-JennyMultilingualNeural"},
  {name: "Jenny", code: "en-US-JennyNeural"},
  {name: "Guy", code: "en-US-GuyNeural"},
  {name: "Aria", code: "en-US-AriaNeural"},
  {name: "Davis", code: "en-US-DavisNeural"},
  {name: "Amber", code: "en-US-AmberNeural"},
  {name: "Ana (Child)", code: "en-US-AnaNeural"},
  {name: "Andrew", code: "en-US-AndrewNeural"},
  {name: "Ashley", code: "en-US-AshleyNeural"},
  {name: "Brandon", code: "en-US-BrandonNeural"},
  {name: "Brian", code: "en-US-BrianNeural"},
  {name: "Christopher", code: "en-US-ChristopherNeural"},
  {name: "Cora", code: "en-US-CoraNeural"},
  {name: "Elizabeth", code: "en-US-ElizabethNeural"},
  {name: "Emma", code: "en-US-EmmaNeural"},
  {name: "Eric", code: "en-US-EricNeural"},
  {name: "Jacob", code: "en-US-JacobNeural"},
  {name: "Jane", code: "en-US-JaneNeural"},
  {name: "Jason", code: "en-US-JasonNeural"},
  {name: "Michelle", code: "en-US-MichelleNeural"},
  {name: "Monica", code: "en-US-MonicaNeural"},
  {name: "Nancy", code: "en-US-NancyNeural"},
  {name: "Roger", code: "en-US-RogerNeural"},
  {name: "Sara", code: "en-US-SaraNeural"},
  {name: "Steffan", code: "en-US-SteffanNeural"},
  {name: "Tony", code: "en-US-TonyNeural"},
  {name: "AI Generate 1", code: "en-US-AIGenerate1Neural1"},
  {name: "AI Generate 2", code: "en-US-AIGenerate2Neural1"},
  {name: "Blue", code: "en-US-BlueNeural1"},
  {name: "Jenny Multi Lingua V2", code: "en-US-JennyMultilingualV2Neural"},
  {name: "Ryan Multi Lingua", code: "en-US-RyanMultilingualNeural"}
];

export const languageData = [
  {name: "English (United States)", code: "en-US"},
  {name: "Hindi (United States)", code: "en-US"},
];